export { Home } from "./Home";
export { default as DashboardPage } from "./DashboardPage";
export { EspeciesPage } from "./EspeciesPage";
export { PresentacionesPage } from "./PresentacionesPage";
export { default as CatalogosPage } from "./CatalogosPage";
export { default as VariantesPage } from "./VariantesPage";
export { default as IngresosPage } from "./ingresos/IngresosPage";
export { default as IngresoDetallePage } from "./ingresos/IngresoDetallePage";
export { default as EditarIngresosPage } from "./ingresos/EditarIngresosPage";
export { default as SalidasPage } from "./salidas/SalidasPage";
export { default as SalidaDetallePage } from "./salidas/SalidaDetallePage";
export { default as EditarSalidasPage } from "./salidas/EditarSalidasPage";
export { default as StockPage } from "./StockPage";
export { default as ReportesPage } from "./ReportesPage";
export { default as NewPartePage } from "./partes/NewPartePage";
export { default as NewControlPage } from "./control/NewControlPage";
