export { Home } from "./Home";
export { default as DashboardPage } from "./DashboardPage";
export { EspeciesPage } from "./EspeciesPage";
export { PresentacionesPage } from "./PresentacionesPage";
export { default as CatalogosPage } from "./CatalogosPage";
export { default as VariantesPage } from "./VariantesPage";
export { default as IngresosPage } from "./IngresosPage";
export { default as SalidasPage } from "./SalidasPage";
export { default as StockPage } from "./StockPage";
export { default as ReportesPage } from "./ReportesPage";
export { default as NewPartePage } from "./partes/NewPartePage";
